spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/testTable
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  logging:
    level:
      org.hibernate:
        type.descriptor.sql: trace #show parameter binding
        SQL: DEBUG